services:
  db:
    image: postgres:17-alpine
    container_name: multi_tenancy_postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
    container_name: multi_tenancy_django
    command: python3 /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  pgdata:
